networks:
  na-comanda-net:
    driver: bridge

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PWD}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PWD}
    networks:
      - na-comanda-net
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - na-comanda-net
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - CUSTOMER_SERVICE_URL=${CUSTOMER_SERVICE_URL}
      - PAYMENT_SERVICE_URL=${PAYMENT_SERVICE_URL}
      - ORDER_SERVICE_URL=${ORDER_SERVICE_URL}
      - MERCADOPAGO_CLIENT_ID=${MERCADOPAGO_CLIENT_ID}
      - MERCADOPAGO_SECRET_ID=${MERCADOPAGO_SECRET_ID}

volumes:
  db-data:

